apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
      - name: demo-server
        image: demo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ENV
          value: dns
        ports:
        - containerPort: 80
