# File architecture
# - Common section 1: currently only the "http_archive" rule.
# - Common section 2: http_archive rules.
# - Setup Golang & Gazelle.
# - Setup other languages. For each lanuage:
#   - Setup launage.
#   - install launage dependencies.
#   - Setup Gazelle plugin for other languages.


# Common section 1
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


## rules_go
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "6dc2da7ab4cf5d7bfc7c949776b1b7c733f05e56edc4bcd9022bb249d2e2a996",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.39.1/rules_go-v0.39.1.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.39.1/rules_go-v0.39.1.zip",
    ],
)

## rules_bazel_gazelle.
http_archive(
    name = "bazel_gazelle",
    sha256 = "727f3e4edd96ea20c29e8c2ca9e8d2af724d8c7778e7923a854b2c80952bc405",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.30.0/bazel-gazelle-v0.30.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.30.0/bazel-gazelle-v0.30.0.tar.gz",
    ],
)


## Lang:Python
http_archive(
    name = "rules_python",
    sha256 = "863ba0fa944319f7e3d695711427d9ad80ba92c6edd0b7c7443b84e904689539",
    strip_prefix = "rules_python-0.22.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.22.0/rules_python-0.22.0.tar.gz",
)
## Lang:Gazelle-Python-Plugin
http_archive(
    name = "rules_python_gazelle_plugin",
    sha256 = "863ba0fa944319f7e3d695711427d9ad80ba92c6edd0b7c7443b84e904689539",
    strip_prefix = "rules_python-0.22.0/gazelle",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.22.0/rules_python-0.22.0.tar.gz",
)

# Language setup

# High priority language:
# - Golang
# - Gazelle plugin initialization
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

############################################################
# Define your own dependencies here using go_repository.
# Else, dependencies declared by rules_go/gazelle will be used.
# The first declaration of an external repository "wins".
############################################################

go_rules_dependencies()

go_register_toolchains(version = "1.20.4")

gazelle_dependencies()

# Regular priority setup.

## Lang:Python step 1
# Copied from https://github.com/bazelbuild/rules_python/releases/tag/0.22.0
load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

## Lang:Python step 2
python_register_toolchains(
    name = "python3_11",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.11",
)

load("@python3_11//:defs.bzl", "interpreter")

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "my_pip",
    python_interpreter_target = interpreter,
    requirements_lock = "//jupyter-run:requirements_lock.txt",
)
# Load the starlark macro which will define your dependencies.
load("@my_pip//:requirements.bzl", "install_deps")
# Call it to define repos for your requirements.
install_deps()

## Plugin:Gazelle step 1
## - Dependencies: Lang:Python

# To compile the rules_python gazelle extension from source,
# we must fetch some third-party go dependencies that it uses.
load("@rules_python_gazelle_plugin//:deps.bzl", _py_gazelle_deps = "gazelle_deps")

_py_gazelle_deps()


