# File architecture
# - Common section 1: currently only the "http_archive" rule.
# - Common section 2: http_archive rules.
# - Setup Golang & Gazelle.
# - Setup other languages. For each lanuage:
#   - Setup launage.
#   - install launage dependencies.
#   - Setup Gazelle plugin for other languages.


# Common section 1
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


###################################
# Section for updating rules

# https://github.com/bazelbuild/rules_go/releases/tag/v0.41.0
# https://github.com/bazelbuild/bazel-gazelle
_RULES_GO_SHA256 = "278b7ff5a826f3dc10f04feaf0b70d48b68748ccd512d7f98bf442077f043fe3"
_RULES_GO_VERSION = "v0.41.0"

_RULES_BAZEL_GAZELLE_SHA256 = "d3fa66a39028e97d76f9e2db8f1b0c11c099e8e01bf363a923074784e451f809"
_RULES_BAZEL_GAZELLE_VERSION = "v0.33.0"

# https://github.com/bazelbuild/rules_python/releases/tag/0.25.0
_RULES_PYTHON_SHA256 = "5868e73107a8e85d8f323806e60cad7283f34b32163ea6ff1020cf27abef6036"
_RULES_PYTHON_VERSION = "0.25.0"

_RULES_PYTHON_GAZELLE_PLUGIN_SHA256 = "5868e73107a8e85d8f323806e60cad7283f34b32163ea6ff1020cf27abef6036"
_RULES_PYTHON_GAZELLE_PLUGIN_VERSION = "0.25.0"
###################################

## rules_go
http_archive(
    name = "io_bazel_rules_go",
    sha256 = _RULES_GO_SHA256,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/{version}/rules_go-{version}.zip".format(version=_RULES_GO_VERSION),
        "https://github.com/bazelbuild/rules_go/releases/download/{version}/rules_go-{version}.zip".format(version=_RULES_GO_VERSION),
    ],
)

## rules_bazel_gazelle.
http_archive(
    name = "bazel_gazelle",
    sha256 = _RULES_BAZEL_GAZELLE_SHA256,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/{version}/bazel-gazelle-{version}.tar.gz".format(version=_RULES_BAZEL_GAZELLE_VERSION),
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/{version}/bazel-gazelle-{version}.tar.gz".format(version=_RULES_BAZEL_GAZELLE_VERSION),
    ],
)


## Lang:Python
http_archive(
    name = "rules_python",
    sha256 = _RULES_PYTHON_SHA256,
    strip_prefix = "rules_python-{version}".format(version=_RULES_PYTHON_VERSION),
    url = "https://github.com/bazelbuild/rules_python/releases/download/{version}/rules_python-{version}.tar.gz".format(version=_RULES_PYTHON_VERSION),
)
## Lang:Gazelle-Python-Plugin
http_archive(
    name = "rules_python_gazelle_plugin",
    sha256 = _RULES_PYTHON_GAZELLE_PLUGIN_SHA256,
    strip_prefix = "rules_python-{version}/gazelle".format(version=_RULES_PYTHON_GAZELLE_PLUGIN_VERSION),
    url = "https://github.com/bazelbuild/rules_python/releases/download/{version}/rules_python-{version}.tar.gz".format(version=_RULES_PYTHON_GAZELLE_PLUGIN_VERSION),
)

# Language setup

# High priority language:
# - Golang
# - Gazelle plugin initialization
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

############################################################
# Define your own dependencies here using go_repository.
# Else, dependencies declared by rules_go/gazelle will be used.
# The first declaration of an external repository "wins".
############################################################

go_rules_dependencies()

go_register_toolchains(version = "1.20.5")

# Use this if using WORKSPACE.bazel
# gazelle_dependencies(go_repository_default_config = "//:WORKSPACE.bazel")
gazelle_dependencies()

# Regular priority setup.

## Lang:Python step 1
# Copied from https://github.com/bazelbuild/rules_python/releases/tag/0.22.0
load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

## Lang:Python step 2
python_register_toolchains(
    name = "python3_11",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.11",
)

load("@python3_11//:defs.bzl", "interpreter")

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "my_pip",
    python_interpreter_target = interpreter,
    requirements_lock = "//jupyter-run:requirements_lock.txt",
)
# Load the starlark macro which will define your dependencies.
load("@my_pip//:requirements.bzl", "install_deps")
# Call it to define repos for your requirements.
install_deps()

## Plugin:Gazelle step 1
## - Dependencies: Lang:Python

# To compile the rules_python gazelle extension from source,
# we must fetch some third-party go dependencies that it uses.
load("@rules_python_gazelle_plugin//:deps.bzl", _py_gazelle_deps = "gazelle_deps")

_py_gazelle_deps()


