"""
Django settings for django_demo_1_11 project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys

ROOT_DIR = "/Users/mingzhu/rh/"
sys.path.append(os.path.join(ROOT_DIR, "arbiter"))
sys.path.append(os.path.join(ROOT_DIR, "tracing-python"))

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xzajy(k4mefs%_rt3qan-r^xt%r5i%@85ujn=fcrhij1&ktoqh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.demo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_demo_1_11.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_demo_1_11.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "dft",
        "USER": "dft",
        "PASSWORD": "password",
        "HOST": "localhost",
        "PORT": "5432",
    },
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


#################################################
# New settings
SUPPORT_EMAIL = "a@b.com"

STATSD_HOST = "localhost"
STATSD_PORT = 9002

TRACING = {
            "enabled": True,
            "service_name": "demo-app",
            "metrics_prefix": "brokeback",
            "jaeger": {
                "sampler": {
                    "type": "probabilistic",
                    "param": 1,
                },
                "max_tag_value_length": 4000,
                "logging": False,
                "reporter_queue_size": 1000,
                "reporter_batch_size": 5,
                "local_agent": {
                    "reporting_host": "localhost",
                    "reporting_port": 6831,
                    "sampling_port": 5778,
                },
            },
            "statsd_middleware_rate": 1,
            "db_span_comment_enabled": True,
            "traceback_rate": 1,
            "deterministic_tracebacks": 1,
            "traced_methods": [
                "django.db.backends.base.base.BaseDatabaseWrapper.run_and_clear_commit_hooks",
                "kombu.connection.Connection._establish_connection",
                "zardoz.drivers.c_kafka.producer.BrokebackConfluentProducer.send_messages_as_list",
                "zardoz.drivers.c_kafka.producer.BrokebackConfluentProducer.send_messages",
            ],
            "http_client": {"enabled": True, "default_timeout_seconds": 5,},
        }

USE_CELERY = True
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
# Extra: by pass celery
CELERY_ALWAYS_EAGER = True
CELERY_ARG_VALIDATE_FUNC = None

SYNC_DELAY_SECONDS = 1
SYNC_DELAY_MAX_SECONDS = 3

