set nobackup
set nowritebackup
"set noswapfile
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smarttab
set hlsearch
set expandtab

filetype indent on
filetype on
filetype plugin on
